name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          skip_install: true
          use_bundler: true
          reviewdog_flags: -fail-level=any

      - name: Run RSpec
        run: bundle exec rspec
